spring:
  application:
    name: jogo-service

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: jogo-service
    prefer-ip-address: false

server:
  port: 8081
