server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: jogo-service
          uri: lb://jogo-service
          predicates:
            - Path=/api/jogos/**
          filters:
            - StripPrefix=1

        - id: conquista-service
          uri: lb://conquista-service
          predicates:
            - Path=/api/conquistas/**
          filters:
            - StripPrefix=1
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                          allowedOrigins: "*"
                          allowedMethods: "*"
                          allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/  # ← Critical: Use container name
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    eureka:
      enabled: false

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG
