server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: jogo-service
          uri: lb://JOGO-SERVICE
          predicates:
            - Path=/api/jogos/**
          filters:
            - StripPrefix=1

        - id: conquista-service
          uri: lb://CONQUISTA-SERVICE
          predicates:
            - Path=/api/conquistas/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: false
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    eureka:
      enabled: false

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG